### ISSUE TITLE
.text on json decode returns null

### ISSUE THREAD

**Issue by GroovinChip** [ThinkDigitalSoftware/tavern#16]
On line 29 in `html_parsing_client`:
```var script = json.decode(document.querySelector('body > main > script').text);```
`.text` is returning null for the following package:
`flutter_naver_login`

I can attach the full code that I'm working with in a pastebin if you need.

The full stack trace is below:
```
I/flutter (28795): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28795): The following assertion was thrown building AnimatedPhysicalModel(duration: 200ms, shape: rectangle,
I/flutter (28795): borderRadius: BorderRadius.zero, elevation: 0.0, color: Color(0xff122030), animateColor: false,
I/flutter (28795): shadowColor: Color(0xff000000), animateShadowColor: true, state:
I/flutter (28795): _AnimatedPhysicalModelState#9f73c(ticker inactive)):
I/flutter (28795): A RenderNestedScrollViewViewport expected a child of type RenderSliver but received a child of type
I/flutter (28795): RenderPhysicalModel.
I/flutter (28795): RenderObjects expect specific types of children because they coordinate with their children during
I/flutter (28795): layout and paint. For example, a RenderSliver cannot be the child of a RenderBox because a
I/flutter (28795): RenderSliver does not understand the RenderBox layout protocol.
I/flutter (28795): 
I/flutter (28795): The RenderNestedScrollViewViewport that expected a RenderSliver child was created by:
I/flutter (28795):   NestedScrollViewViewport ← IgnorePointer-[GlobalKey#b0b37] ← Semantics ← Listener ←
I/flutter (28795): _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#24f19] ← Listener
I/flutter (28795): ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#8fc5f] ← RepaintBoundary ← CustomPaint ←
I/flutter (28795): RepaintBoundary ← ⋯
I/flutter (28795): 
I/flutter (28795): The RenderPhysicalModel that did not match the expected child type was created by:
I/flutter (28795):   PhysicalModel ← AnimatedPhysicalModel ← Material ← PubHeader ← NestedScrollViewViewport ←
I/flutter (28795): IgnorePointer-[GlobalKey#b0b37] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (28795): RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#24f19] ← Listener ← _ScrollableScope ←
I/flutter (28795): ⋯
I/flutter (28795): 
I/flutter (28795): 
I/flutter (28795): When the exception was thrown, this was the stack:
I/flutter (28795): #0      _RenderViewportBase&RenderBox&ContainerRenderObjectMixin.debugValidateChild.<anonymous closure> (package:flutter/src/rendering/object.dart:2852:9)
I/flutter (28795): #1      _RenderViewportBase&RenderBox&ContainerRenderObjectMixin.debugValidateChild (package:flutter/src/rendering/object.dart:2869:6)
I/flutter (28795): #2      MultiChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:5037:25)
I/flutter (28795): #3      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4832:35)
I/flutter (28795): #4      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4598:5)
I/flutter (28795): #5      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:11)
I/flutter (28795): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819:5)
I/flutter (28795): #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3961:11)
I/flutter (28795): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814:5)
I/flutter (28795): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819:5)
I/flutter (28795): #18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3961:11)
I/flutter (28795): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814:5)
I/flutter (28795): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819:5)
I/flutter (28795): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3961:11)
I/flutter (28795): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814:5)
I/flutter (28795): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #28     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5079:32)
I/flutter (28795): #29     _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:186:11)
I/flutter (28795): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973:14)
I/flutter (28795): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973:14)
I/flutter (28795): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973:14)
I/flutter (28795): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973:14)
I/flutter (28795): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819:5)
I/flutter (28795): #47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3961:11)
I/flutter (28795): #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814:5)
I/flutter (28795): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973:14)
I/flutter (28795): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819:5)
I/flutter (28795): #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814:5)
I/flutter (28795): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #60     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973:14)
I/flutter (28795): #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #63     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973:14)
I/flutter (28795): #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973:14)
I/flutter (28795): #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #69     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4973:14)
I/flutter (28795): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819:5)
I/flutter (28795): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814:5)
I/flutter (28795): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819:5)
I/flutter (28795): #81     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3961:11)
I/flutter (28795): #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814:5)
I/flutter (28795): #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819:5)
I/flutter (28795): #88     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3961:11)
I/flutter (28795): #89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814:5)
I/flutter (28795): #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #94     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819:5)
I/flutter (28795): #95     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814:5)
I/flutter (28795): #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819:5)
I/flutter (28795): #101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814:5)
I/flutter (28795): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819:5)
I/flutter (28795): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814:5)
I/flutter (28795): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #112    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3819:5)
I/flutter (28795): #113    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3961:11)
I/flutter (28795): #114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3814:5)
I/flutter (28795): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #116    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5079:32)
I/flutter (28795): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3053:14)
I/flutter (28795): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2856:12)
I/flutter (28795): #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3847:16)
I/flutter (28795): #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3657:5)
I/flutter (28795): #121    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2315:33)
I/flutter (28795): #122    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (28795): #123    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (28795): #124    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (28795): #125    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (28795): #126    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (28795): #130    _invoke (dart:ui/hooks.dart:225:10)
I/flutter (28795): #131    _drawFrame (dart:ui/hooks.dart:183:3)
I/flutter (28795): (elided 3 frames from package dart:async)
I/flutter (28795): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (28795): Another exception was thrown: A RenderNestedScrollViewViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
I/chatty  (28795): uid=10341(software.thinkdigital.pub_dev_client) Thread-2 identical 1 line
I/flutter (28795): Another exception was thrown: A RenderNestedScrollViewViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
I/flutter (28795): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3659 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/chatty  (28795): uid=10341(software.thinkdigital.pub_dev_client) Thread-2 identical 8 lines
I/flutter (28795): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3659 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (28795): Another exception was thrown: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following child:
I/flutter (28795): Another exception was thrown: A RenderFlex overflowed by 799397 pixels on the bottom.
I/flutter (28795): Another exception was thrown: Updated layout information required for RenderErrorBox#f4972 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
I/flutter (28795): NoSuchMethodError: The getter 'text' was called on null.
I/flutter (28795): Receiver: null
I/flutter (28795): Tried calling: text```

**Comment by ThinkDigitalSoftware** [comment]
fixed
